workflows:
  ios-workflow:
    name: iOS Workflow for Strawberry
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      node: 14.15.5
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install
      - name: Build React
        script: |
          npm run build
      - name: Install capacitor for iOS
        script: |
          npm install @capacitor/ios
      - name: Add iOS to capacitor
        script: |
          npx cap add ios
      - name: Sync capacitor
        script: |
          npx cap sync
      - name: Cocoapods installation
        script: |
          cd ios/App && pod install
      - name: Build Xcode
        script: |
          xcodebuild build -workspace "MyXcodeWorkspace.xcworkspace" -scheme "MyScheme" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - everettflynn25@gmail.com
      scripts:
        - echo 'Post-publish script'
